### ISSUE TITLE
Tabular Format

### ISSUE THREAD

**Issue by Arkanyus** [mikebanks/AbuseIPdbSCAN#8]
How do I get a table like in your report examples with bulk IP checks?

The outputs I'm getting are 'ipAddress': '0.0.0.0', 'isPublic': True
Which I can only get to display in Excel as 'ipAddress': '0.0.0.0' | 'isPublic': True
As opposed to 
'ipAddress' | 'isPublic': 
'0.0.0.0' | True

I can't review large results in the current format so I must be doing something wrong.

**Comment by mikebanks** [comment]
Which report is it that you are explicitly referring to, and what command are you currently using?

**Comment by Arkanyus** [comment]
Sorry, the .csv report. When I check the raw view for that page That doesnt match the delimiters in my .csv output.

Command im using is: python3 AbuseIPDB.py -f "[inputList]" > "[myOutput]"

Tried with and without -c for csv.

Thanks

**Comment by mikebanks** [comment]
Ahh. So the table you see [here](https://github.com/mikebanks/AbuseIPdbSCAN/blob/master/reports/example_list.csv) is formatting that GitHub does on their website. If you press the raw button you will see what the file actually looks like.

If you use the -c or the -t flag it should output in a format to where you open it up in excel it should look similar. JSON or JSONL is the preferrable output format since the comment field can throw some unintended output. Soon I'll disable the comment field and only include it on the flag for CSV and TSV.

**Comment by Arkanyus** [comment]
Ah right, d'oh. 

I'm getting a "expected one argument" error when I try to run several flags, is this faulty:

            **python3 AbuseIPDB.py -c -f "[inputList]" > "[myOutput]"**

also tried

            **python3 AbuseIPDB.py -cf "[inputList]" > "[myOutput]"**
            **python3 AbuseIPDB.py  -f "[inputList]" -c > "[myOutput]"**

Seemed to work ok for your example which i ran to test multiple flags.

Thanks

**Comment by mikebanks** [comment]
Each flag is looking for a text argument for a filename:
```
python3 AbuseIPDB.py  -f "/path/to/file" -c "/path/to/file.csv"`
```

**Comment by Arkanyus** [comment]
Awesome, I've just hit the AbuseIPDB rate limit whilst running the working command hahah

Thanks for your help, appreciate the time and speed of the replies 👍
